import Link from "next/link";

import { providerLabels, type ProviderKey } from "@/features/account-grants/fixtures";
import { getAgencyAccountManagement } from "@/features/account-grants/queries";
import { addAgencyAccount, removeAgencyAccount, seedAccountFixtures, toggleMemberGrant } from "./actions";

export default async function AgencyAccountsPage({ params }: PageProps<"/dashboard/agencies/[agencyId]/accounts">) {
  const { agencyId } = await params;
  const { manager, catalog, clients, grants } = await getAgencyAccountManagement(agencyId);
  const grantedKeys = new Set(grants.map((grant) => `${grant.agencyAccountId}:${grant.memberId}`));
  const availableAccounts = catalog.filter((account) => account.agencyAccountId);

  return (
    <main className="min-h-screen bg-slate-50 px-5 py-8 lg:px-8">
      <div className="mx-auto max-w-6xl">
        <Link className="text-sm font-medium text-slate-500 hover:text-slate-950" href={`/dashboard/agencies/${agencyId}`}>← Agency users</Link>
        <div className="mb-6 mt-5"><p className="text-sm font-medium text-slate-500">Account access</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Source-account grants</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Agency membership does not grant analytics data. Make source accounts available to this agency, then grant each client only the accounts they should see.</p></div>

        {catalog.length === 0 && manager.role === "superadmin" && <section className="rounded-xl border border-dashed border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Install the Phase 2 fixture catalog</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">This creates non-secret sample accounts for all five planned providers. Airbyte discovery replaces these fixtures in Phase 3 and Phase 4.</p><form action={seedAccountFixtures} className="mt-4"><input name="agencyId" type="hidden" value={agencyId} /><button className="button-primary w-auto px-5" type="submit">Install fixture accounts</button></form></section>}

        {catalog.length > 0 && <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Account catalog</h2><p className="mt-1 text-sm text-slate-500">{availableAccounts.length} of {catalog.length} accounts available to this agency</p></div><div className="divide-y divide-slate-100">{catalog.map((account) => <div className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" key={account.id}><div><p className="font-medium text-slate-900">{account.name}</p><p className="mt-1 text-sm text-slate-500">{providerLabels[account.provider as ProviderKey]} · {account.externalAccountId}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${account.agencyAccountId ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{account.agencyAccountId ? "Available" : "Not available"}</span>{manager.role === "superadmin" && <form action={account.agencyAccountId ? removeAgencyAccount : addAgencyAccount}><input name="agencyId" type="hidden" value={agencyId} />{account.agencyAccountId ? <input name="agencyAccountId" type="hidden" value={account.agencyAccountId} /> : <input name="sourceAccountId" type="hidden" value={account.id} />}<button className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50" type="submit">{account.agencyAccountId ? "Remove from agency" : "Make available"}</button></form>}</div></div>)}</div></section>}

        <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Client grants</h2><p className="mt-1 text-sm text-slate-500">Granting an account here controls future dashboards and scheduled reports.</p></div>{clients.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">Add a client user before assigning accounts.</p> : availableAccounts.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">No source accounts are available to this agency.</p> : <div className="divide-y divide-slate-100">{clients.map((client) => <div className="px-5 py-5" key={client.memberId}><div><p className="font-medium text-slate-900">{client.name}</p><p className="mt-1 text-sm text-slate-500">{client.email}</p></div><div className="mt-4 grid gap-2 md:grid-cols-2">{availableAccounts.map((account) => { const key = `${account.agencyAccountId}:${client.memberId}`; const granted = grantedKeys.has(key); return <div className="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-3" key={account.id}><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{account.name}</p><p className="text-xs text-slate-500">{providerLabels[account.provider as ProviderKey]}</p></div><form action={toggleMemberGrant}><input name="agencyId" type="hidden" value={agencyId} /><input name="agencyAccountId" type="hidden" value={account.agencyAccountId ?? ""} /><input name="memberId" type="hidden" value={client.memberId} /><input name="enabled" type="hidden" value={granted ? "false" : "true"} /><button className={`ml-3 rounded-lg px-3 py-2 text-xs font-semibold ${granted ? "border border-slate-200 text-slate-600 hover:bg-slate-50" : "bg-slate-950 text-white hover:bg-slate-800"}`} type="submit">{granted ? "Revoke" : "Grant"}</button></form></div>; })}</div></div>)}</div>}</section>
      </div>
    </main>
  );
}
