import Link from "next/link";

import { providerKeys, providerLabels } from "@/features/account-grants/fixtures";
import { getAgencyAccountManagement } from "@/features/account-grants/queries";
import { loadAccountSearchParams, serializeAccountSearchParams } from "@/features/account-grants/search-params";
import { addAgencyAccount, removeAgencyAccount, seedAccountFixtures, toggleMemberGrant } from "./actions";

export default async function AgencyAccountsPage({ params, searchParams }: PageProps<"/dashboard/agencies/[agencyId]/accounts">) {
  const [{ agencyId }, filters] = await Promise.all([params, loadAccountSearchParams(searchParams)]);
  const { manager, catalog, clients, grants, page, totalPages, catalogTotal, sourceTotal, clientTotal, clientPageSize } = await getAgencyAccountManagement(agencyId, filters);
  const grantedKeys = new Set(grants.map((grant) => `${grant.agencyAccountId}:${grant.memberId}`));
  const availableAccounts = catalog.filter((account) => account.agencyAccountId);
  const previousUrl = serializeAccountSearchParams(`/dashboard/agencies/${agencyId}/accounts`, { ...filters, page: Math.max(1, page - 1) });
  const nextUrl = serializeAccountSearchParams(`/dashboard/agencies/${agencyId}/accounts`, { ...filters, page: Math.min(totalPages, page + 1) });

  return (
    <main className="min-h-screen bg-slate-50 px-5 py-8 lg:px-8">
      <div className="mx-auto max-w-6xl">
        <Link className="text-sm font-medium text-slate-500 hover:text-slate-950" href={`/dashboard/agencies/${agencyId}`}>← Agency users</Link>
        <div className="mb-6 mt-5"><p className="text-sm font-medium text-slate-500">Account access</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Source-account grants</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Agency membership does not grant analytics data. Make source accounts available to this agency, then grant each client only the accounts they should see.</p></div>

        {sourceTotal === 0 && manager.role === "superadmin" && <section className="rounded-xl border border-dashed border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Install the Phase 2 fixture catalog</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">This creates non-secret sample accounts for all five planned providers. Airbyte discovery replaces these fixtures in Phase 3 and Phase 4.</p><form action={seedAccountFixtures} className="mt-4"><input name="agencyId" type="hidden" value={agencyId} /><button className="button-primary w-auto px-5" type="submit">Install fixture accounts</button></form></section>}

        {sourceTotal > 0 && <>
          <form className="mb-4 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_220px_180px_auto] md:items-end" method="get">
            <label className="text-sm font-medium text-slate-700">Search accounts<input className="field mt-1.5" defaultValue={filters.q} name="q" placeholder="Account name or provider ID" /></label>
            <label className="text-sm font-medium text-slate-700">Provider<select className="field mt-1.5" defaultValue={filters.provider ?? ""} name="provider"><option value="">All providers</option>{providerKeys.map((provider) => <option key={provider} value={provider}>{providerLabels[provider]}</option>)}</select></label>
            {manager.role === "superadmin" ? <label className="text-sm font-medium text-slate-700">Availability<select className="field mt-1.5" defaultValue={filters.availability} name="availability"><option value="all">All accounts</option><option value="available">Available</option><option value="unavailable">Not available</option></select></label> : <div />}
            <div className="flex gap-2"><button className="button-primary w-auto px-4" type="submit">Apply</button><Link className="inline-flex items-center rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50" href={`/dashboard/agencies/${agencyId}/accounts`}>Clear</Link></div>
          </form>

          <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Account catalog</h2><p className="mt-1 text-sm text-slate-500">{catalogTotal} matching {catalogTotal === 1 ? "account" : "accounts"}</p></div>{catalog.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">No source accounts match these filters.</p> : <div className="divide-y divide-slate-100">{catalog.map((account) => <div className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" key={account.id}><div><p className="font-medium text-slate-900">{account.name}</p><p className="mt-1 text-sm text-slate-500">{providerLabels[account.provider]} · {account.externalAccountId}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${account.agencyAccountId ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{account.agencyAccountId ? "Available" : "Not available"}</span>{manager.role === "superadmin" && <form action={account.agencyAccountId ? removeAgencyAccount : addAgencyAccount}><input name="agencyId" type="hidden" value={agencyId} />{account.agencyAccountId ? <input name="agencyAccountId" type="hidden" value={account.agencyAccountId} /> : <input name="sourceAccountId" type="hidden" value={account.id} />}<button className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50" type="submit">{account.agencyAccountId ? "Remove from agency" : "Make available"}</button></form>}</div></div>)}</div>}<div className="flex items-center justify-between border-t border-slate-200 px-5 py-3 text-sm"><p className="text-slate-500">Page {page} of {totalPages}</p><div className="flex gap-2">{page > 1 ? <Link className="rounded-lg border border-slate-200 px-3 py-2 font-medium text-slate-700 hover:bg-slate-50" href={previousUrl}>Previous</Link> : <span className="cursor-not-allowed rounded-lg border border-slate-100 px-3 py-2 text-slate-300">Previous</span>}{page < totalPages ? <Link className="rounded-lg border border-slate-200 px-3 py-2 font-medium text-slate-700 hover:bg-slate-50" href={nextUrl}>Next</Link> : <span className="cursor-not-allowed rounded-lg border border-slate-100 px-3 py-2 text-slate-300">Next</span>}</div></div></section>
        </>}

        <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
          <div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Client grants</h2><p className="mt-1 text-sm text-slate-500">Granting an account here controls future dashboards and scheduled reports.</p><form className="mt-3 flex max-w-lg gap-2" method="get"><input name="q" type="hidden" value={filters.q} />{filters.provider && <input name="provider" type="hidden" value={filters.provider} />}{manager.role === "superadmin" && <input name="availability" type="hidden" value={filters.availability} />}<input className="field" defaultValue={filters.client} name="client" placeholder="Search clients by name or email" /><button className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50" type="submit">Find client</button></form>{clientTotal > clientPageSize && <p className="mt-2 text-xs text-slate-500">Showing the first {clientPageSize} matches. Refine the client search to narrow the list.</p>}</div>
          {clients.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">{filters.client ? "No client users match this search." : "Add a client user before assigning accounts."}</p> : availableAccounts.length === 0 ? <p className="px-5 py-10 text-center text-sm text-slate-500">No available source accounts are shown. Adjust the account filters or ask a superadmin to make accounts available.</p> : <div className="divide-y divide-slate-100">{clients.map((client) => <div className="px-5 py-5" key={client.memberId}><div><p className="font-medium text-slate-900">{client.name}</p><p className="mt-1 text-sm text-slate-500">{client.email}</p></div><div className="mt-4 grid gap-2 md:grid-cols-2">{availableAccounts.map((account) => { const key = `${account.agencyAccountId}:${client.memberId}`; const granted = grantedKeys.has(key); return <div className="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-3" key={account.id}><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{account.name}</p><p className="text-xs text-slate-500">{providerLabels[account.provider]}</p></div><form action={toggleMemberGrant}><input name="agencyId" type="hidden" value={agencyId} /><input name="agencyAccountId" type="hidden" value={account.agencyAccountId ?? ""} /><input name="memberId" type="hidden" value={client.memberId} /><input name="enabled" type="hidden" value={granted ? "false" : "true"} /><button className={`ml-3 rounded-lg px-3 py-2 text-xs font-semibold ${granted ? "border border-slate-200 text-slate-600 hover:bg-slate-50" : "bg-slate-950 text-white hover:bg-slate-800"}`} type="submit">{granted ? "Revoke" : "Grant"}</button></form></div>; })}</div></div>)}</div>}
        </section>
      </div>
    </main>
  );
}
